
package unidades;

import java.text.DecimalFormat;

public class Convertidor extends javax.swing.JFrame {
    int tipo;
    double in;
    double out;
    String de;
    String a;

    

    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbin = new javax.swing.JComboBox<>();
        cbout = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtin = new javax.swing.JTextField();
        txtout = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De" }));

        cbout.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/actualizar (1) (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtin.setText("0");
        txtin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focus(evt);
            }
        });

        txtout.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtout.setToolTipText("");
        txtout.setAutoscrolls(false);
        txtout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtout.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        txtout.setFocusable(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/metro.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/escala.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/presion.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/temperatura.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/velocidad.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/latido-del-corazon (1).png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/ram.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/reloj.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/matematicas (1).png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unidades/iconos/volumen.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setText("Convertidor de Unidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtout, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtin)
                    .addComponent(txtout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tipo !=0){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro", "Metro", "Centimetro", "Milimetro", "Milla", "Yarda", "Pie", "Pulgada" }));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro", "Metro", "Centimetro", "Milimetro", "Milla", "Yarda", "Pie", "Pulgada" }));
            tipo = 0;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (tipo!= 1){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonelada", "Kilogramo", "Gramo", "Miligramo", "Libra", "Onza"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonelada", "Kilogramo", "Gramo", "Miligramo", "Libra", "Onza"}));
            tipo =1;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (tipo != 2){ 
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atmosfera", "Bar", "psi", "Milimetros de Mercurio", "Hectopascal/Milibar", "Kilopascal","Pascal"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atmosfera", "Bar", "psi", "Milimetros de Mercurio", "Hectopascal/Milibar", "Kilopascal","Pascal"}));
            tipo =2;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (tipo != 3){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grados Celsius (ºC)", "Gados Fahrenheit (ºF)", "Kelvin (K)"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grados Celsius (ºC)", "Gados Fahrenheit (ºF)", "Kelvin (K)"}));
            tipo =3;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (tipo != 4){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro x Hora", "Metros x Segundos", "Milla x Hora", "Pie x Segundo"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro x Hora", "Metros x Segundos", "Milla x Hora", "Pie x Segundo"}));
            tipo =4;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (tipo != 5){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hercio", "Kilohercio", "Megahercio", "Gigahercio"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hercio", "Kilohercio", "Megahercio", "Gigahercio"}));
            tipo = 5;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (tipo != 6){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bit", "Kilobit", "Megabit", "Gigabit", "Terabit", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bit", "Kilobit", "Megabit", "Gigabit", "Terabit", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte"}));
            tipo=6;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (tipo!= 7){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanosegundo", "Microsegundo", "Milisegundo", "Segundo", "Minuto", "Hora", "Dia", "Semana", "Mes", "Año"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanosegundo", "Microsegundo", "Milisegundo", "Segundo", "Minuto", "Hora", "Dia", "Semana", "Mes", "Año"}));
            tipo=7;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (tipo !=8){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro Cuadrado", "Metro Cuadrado", "Centimetro Cuadrado", "Milla Cuadrada", "Yarda Cuadrada", "Pie Cuadrado", "Hectarea"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometro Cuadrado", "Metro Cuadrado", "Centimetro Cuadrado", "Milla Cuadrada", "Yarda Cuadrada", "Pie Cuadrado", "Hectarea"}));
            tipo=8;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (tipo != 9){
            cbin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barril", "Metro Cubico", "Centimetro Cubico", "Litro", "Mililitro"}));
            cbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barril", "Metro Cubico", "Centimetro Cubico", "Litro", "Mililitro"}));
            tipo=9;
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        de = (String) cbin.getSelectedItem();
        a = (String) cbout.getSelectedItem();
        in = Double.parseDouble(txtin.getText());
        
        switch (tipo){
            case 0: out = new Longitud().convertir(de, a, in);     break;
            case 1: out = new Masa().convertir(de, a, in);         break;
            case 2: out = new Presion().convertir(de, a, in);      break;
            case 3: out = new Temperatura().convertir(de, a, in);  break;
            case 4: out = new Velocidad().convertir(de, a, in);    break;
            case 5: out = new Frecuencia().convertir(de, a, in);   break;
            case 6: out = new Memoria().convertir(de, a, in);      break;
            case 7: out = new Tiempo().convertir(de, a, in);       break;
            case 8: out = new Area().convertir(de, a, in);         break;
            case 9: out = new Volumen().convertir(de, a, in);         break;
        }
       txtout.setText(new DecimalFormat("##.#########").format(out));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void focus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focus
        if ("0".equals(txtin.getText())){
            txtin.setText("");
       }
    }//GEN-LAST:event_focus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbin;
    private javax.swing.JComboBox<String> cbout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtin;
    private javax.swing.JTextField txtout;
    // End of variables declaration//GEN-END:variables
}
